trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/"
      api_location: "api"
      output_location: "build"
    env:
      azure_static_web_apps_api_token: $(deployment_token)
